# EXPERIMENT 11
##CATEGORICAL DATA ANALYSIS USING PYTHON
###Ayush Phale
###PRN: 25070123028
##### ENTC A2

In [26]:
import pandas as pd
data = {
    'Order_ID':['01','02','03','04','05','06','07','08','09','010'],
    'Category':['Electronics','Clothing','Electronics','Grocery','Clothing','Electronics','Grocery','Clothing','Electronics','Grocery'],
    'Payemnt_Method':['UPI','Card','UPI','Cash','Card','UPI','Cash','Card','UPI','Cash'],
    'Delivery_Type':['Express','Standard','Express','Standard','Express','Standard','Express','Standard','Express','Standard'],
    'Customer_Type:':['New','Returning','Returning','New','Returning','New','Returning','New','Returning','New']


}
df=pd.DataFrame(data)
print(df)

  Order_ID     Category Payemnt_Method Delivery_Type Customer_Type:
0       01  Electronics            UPI       Express            New
1       02     Clothing           Card      Standard      Returning
2       03  Electronics            UPI       Express      Returning
3       04      Grocery           Cash      Standard            New
4       05     Clothing           Card       Express      Returning
5       06  Electronics            UPI      Standard            New
6       07      Grocery           Cash       Express      Returning
7       08     Clothing           Card      Standard            New
8       09  Electronics            UPI       Express      Returning
9      010      Grocery           Cash      Standard            New

In [9]:
#1. Frequency Count
#Count how mny orders i eah category.

print(df['Category'].value_counts())

Category
Electronics    3
Clothing       3
Grocery        3
Eectronics     1
Name: count, dtype: int64

In [11]:
#2. Unique Values
#Display all unique categories

print(df['Category'].unique())

['Electronics' 'Clothing' 'Grocery' 'Eectronics']

In [14]:
#3. Number of Unique  values
print(df['Category'].nunique())

4

In [27]:
#4. Frequency of Payment methods
print(df['Payemnt_Method'].value_counts())

Payemnt_Method
UPI     4
Card    3
Cash    3
Name: count, dtype: int64

In [18]:
#5. Cross TABULATION
#Category vs payment method
print(pd.crosstab(df['Category'],df['Payment_Method']))

Payment_Method  Card  Cash  UPI
Category
Clothing           3     0    0
Eectronics         0     0    1
Electronics        0     0    3
Grocery            0     3    0

In [28]:
#6. Cross Tabulation (Delivery vs customer type)
print(pd.crosstab(df['Delivery_Type'],df['Customer_Type:']))

Customer_Type:  New  Returning
Delivery_Type
Express           1          4
Standard          4          1

In [19]:
#7. Percentage DIstribution
print(df['Category'].value_counts(normalize=True)*100)

Category
Electronics    30.0
Clothing       30.0
Grocery        30.0
Eectronics     10.0
Name: proportion, dtype: float64

In [29]:
#8. Filtering Data
#Example: Orders from electronics category
electronics_orders= df[df['Category'] == 'Electronics']
print(electronics_orders)

  Order_ID     Category Payemnt_Method Delivery_Type Customer_Type:
0       01  Electronics            UPI       Express            New
2       03  Electronics            UPI       Express      Returning
5       06  Electronics            UPI      Standard            New
8       09  Electronics            UPI       Express      Returning

In [30]:
#Example: Orders from clothing category
clothing_orders= df[df['Category'] == 'Clothing']
print(clothing_orders)

  Order_ID  Category Payemnt_Method Delivery_Type Customer_Type:
1       02  Clothing           Card      Standard      Returning
4       05  Clothing           Card       Express      Returning
7       08  Clothing           Card      Standard            New

In [33]:
#9. Grouping
#Orders by category and payment method
print(df.groupby('Category')['Payemnt_Method'].value_counts())

Category     Payemnt_Method
Clothing     Card              3
Electronics  UPI               4
Grocery      Cash              3
Name: count, dtype: int64

In [32]:
#10. Sorting Data
sorted_df= df.sort_values(by='Category')
print(sorted_df)

  Order_ID     Category Payemnt_Method Delivery_Type Customer_Type:
1       02     Clothing           Card      Standard      Returning
4       05     Clothing           Card       Express      Returning
7       08     Clothing           Card      Standard            New
0       01  Electronics            UPI       Express            New
2       03  Electronics            UPI       Express      Returning
5       06  Electronics            UPI      Standard            New
8       09  Electronics            UPI       Express      Returning
3       04      Grocery           Cash      Standard            New
6       07      Grocery           Cash       Express      Returning
9      010      Grocery           Cash      Standard            New

In [37]:
#SECOND DATASET
import pandas as pd
import numpy as np
df=pd.read_csv('/content/Expt11.csv')
df

   Student  Gender  Department Grade
0       S1    Male         CSE     A
1       S2  Female          IT     B
2       S3  Female         CSE     A
3       S4    Male         ECE     C
4       S5    Male          IT     B
5       S6  Female         CSE     A
6       S7    Male  Mechanical     B
7       S8  Female          IT     A
8       S9    Male         CSE     C
9      S10  Female         ECE     B
10     S11    Male         CSE     A
11     S12  Female          IT     B
12     S13    Male  Mechanical     C
13     S14  Female         CSE     A
14     S15    Male          IT     B
15     S16  Female         ECE     A
16     S17    Male         CSE     B
17     S18  Female          IT     C
18     S19    Male  Mechanical     B
19     S20  Female         CSE     A
20     S21    Male         ECE     C
21     S22  Female          IT     B
22     S23    Male         CSE     A
23     S24  Female  Mechanical     B
24     S25    Male          IT     A
25     S26  Female         CSE     C
26     S27    Male         ECE     B
27     S28  Female          IT     A
28     S29    Male  Mechanical     C
29     S30  Female         CSE     B
30     S31    Male          IT     A
31     S32  Female         ECE     B
32     S33    Male         CSE     A
33     S34  Female  Mechanical     C
34     S35    Male          IT     B
35     S36  Female         CSE     A
36     S37    Male         ECE     B
37     S38  Female          IT     C
38     S39    Male  Mechanical     B
39     S40  Female         CSE     A
40     S41    Male          IT     B
41     S42  Female         ECE     A
42     S43    Male         CSE     C
43     S44  Female  Mechanical     B
44     S45    Male          IT     A
45     S46  Female         CSE     B
46     S47    Male         ECE     C
47     S48  Female          IT     A
48     S49    Male  Mechanical     B
49     S50  Female         CSE     A
50     S51    Male          IT     B
51     S52  Female         ECE     C
52     S53    Male         CSE     A
53     S54  Female  Mechanical     B
54     S55    Male          IT     C
55     S56  Female         CSE     A
56     S57    Male         ECE     B
57     S58  Female          IT     A
58     S59    Male  Mechanical     C
59     S60  Female         CSE     B

In [40]:
df.head()

  Student  Gender Department Grade
0      S1    Male        CSE     A
1      S2  Female         IT     B
2      S3  Female        CSE     A
3      S4    Male        ECE     C
4      S5    Male         IT     B

In [41]:
df.tail()

   Student  Gender  Department Grade
55     S56  Female         CSE     A
56     S57    Male         ECE     B
57     S58  Female          IT     A
58     S59    Male  Mechanical     C
59     S60  Female         CSE     B

In [38]:
#1. Count Students in Each Grade
#Find how many students obtained each grade,
print(df['Gender'].value_counts())

Gender
Male      30
Female    30
Name: count, dtype: int64

In [39]:
#2.Percentage distribution of grades
print(df['Grade'].value_counts(normalize=True)*100)

Grade
B    40.000000
A    36.666667
C    23.333333
Name: proportion, dtype: float64

In [42]:
#3. Number of students in each department
print(df['Department'].value_counts())

Department
CSE           20
IT            18
ECE           11
Mechanical    11
Name: count, dtype: int64

In [43]:
#4. Gender distribution
print(df['Gender'].value_counts())

Gender
Male      30
Female    30
Name: count, dtype: int64

In [44]:
#5. Gender vs Grade analysis
print(pd.crosstab(df['Gender'], df['Grade']))

Grade    A   B  C
Gender
Female  14  11  5
Male     8  13  9

In [45]:
#6. Department vs Gender Analysis
print(pd.crosstab(df['Department'], df['Gender']))

Gender      Female  Male
Department
CSE             12     8
ECE              5     6
IT               9     9
Mechanical       4     7

In [46]:
#7. Department vs Grade percentage
print(pd.crosstab(df['Department'], df['Grade'], normalize=True)*100)

Grade               A          B         C
Department
CSE         21.666667   6.666667  5.000000
ECE          3.333333   8.333333  6.666667
IT          11.666667  13.333333  5.000000
Mechanical   0.000000  11.666667  6.666667

In [48]:
#8. Grouping Data(Departmentwise)
print(df.groupby('Department').size())

Department
CSE           20
ECE           11
IT            18
Mechanical    11
dtype: int64